# Generated by Django 4.1.5 on 2023-02-10 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_remove_choice_question_choice_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choices',
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='albums.question'),
        ),
    ]
