# Generated by Django 4.1.5 on 2023-02-14 12:31

import albums.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0006_alter_question_created_at_alter_question_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='file',
            field=models.FileField(null=True, upload_to='documents/%Y/%m/%d', validators=[albums.models.validate_is_pdf]),
        ),
    ]
