# Generated by Django 4.1.5 on 2023-02-14 12:35

import albums.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0007_question_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='file',
        ),
        migrations.AddField(
            model_name='choice',
            name='file',
            field=models.FileField(null=True, upload_to='documents/%Y/%m/%d', validators=[albums.models.validate_is_pdf]),
        ),
    ]
