# Generated by Django 4.1.5 on 2023-02-15 06:12

import albums.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0008_remove_question_file_choice_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='file',
            field=models.FileField(null=True, upload_to='documents/%Y/%m/%d', validators=[albums.models.validate_extension]),
        ),
    ]
