# Generated by Django 4.1.5 on 2023-02-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0009_alter_choice_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='is_active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
