# Generated by Django 4.1.5 on 2023-02-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0010_musician_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('module_duaration', models.IntegerField()),
                ('class_room', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=False)),
                ('grade', models.IntegerField()),
                ('module', models.ManyToManyField(related_name='student_module', to='albums.module')),
            ],
        ),
    ]
