# Generated by Django 4.1.5 on 2023-02-16 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0011_module_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='module',
            new_name='modules',
        ),
    ]
