# Generated by Django 4.1.5 on 2023-02-16 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0012_rename_module_student_modules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='status',
        ),
    ]
